### ISSUE TITLE
Right-clicking messages is broken in V13?

### ISSUE THREAD

**Issue by shemetz** [shemetz/pf2e-extempore-effects#51]
found on discord - https://discord.com/channels/880968862240239708/880969253765935174/1381153403669057556

> Has the way to inspect rolls changed? Right clicking isn't even bringing up the other options anymore
> Ah yeah it was modules, so much changed I was kinda lost
> Found it, it was the "pf2e Extempore Effects"

**Comment by JacobfromAVS** [comment]
> Still preventing right-clicking unfortunately... throws the following console error when right-clicking on a chat card "Uncaught (in promise) TypeError: li.data is not a fuction [Detected 1 package: pf2e-extempore-effects(1.8.5)]"

I am getting the same thing on V12 too.

**Comment by shemetz** [comment]
FYI, there was a versioning issue with 1.8.x, you should uninstall and reinstall the module to fix some stuff (though I can't guarantee it'll fix this specific bug)!

**Comment by JacobfromAVS** [comment]
I am using extempore-effects version 1.9.2 [image: image.png]


The erron im getting [image: image.png]

**Comment by shemetz** [comment]
@JacobfromAVS your attached error image doesn't work, maybe because you did it through email.  can you try again?

**Comment by Olrar** [comment]
Was about to write my own bug report but saw this thread.  Having the same issue as Jacob.

![Image](https://github.com/user-attachments/assets/c53e6d5a-62b5-4cc1-a762-68d0f1fb8f81)

pf2e extempore effects version 1.9.2
Foundry version 12.343

I currently have Monk's Token Bar installed and enabled.  Is there an issue with having both modules on at the same time?  Had them both on previously but the issue only started recently.

**Comment by Mermut** [comment]
My version was behind because I'd managed to lock the mod. The problem is fixed with 1.10.1.

**Comment by Olrar** [comment]
I'm personally running the game on Forge, rather than directly via the Foundry application.
As far as I can see, Forge only has up to version 1.9.2 and doesn't have version 1.10.1

Not entirely sure why.  Perhaps 1.10.X is only available for version 13 (Would need confirmation) as I'm on v12.

![Image](https://github.com/user-attachments/assets/0512dc1b-98f6-4177-a170-04908f4ce2cd)

**Comment by JacobfromAVS** [comment]
I have restarted and still having the issue. 

![Image](https://github.com/user-attachments/assets/41a81d55-c3b3-4610-a252-efa0c5ab2ab2)

**Comment by shemetz** [comment]
I honestly have no idea why Forge is apparently allowing installs of 1.9.2, after I removed it from every location...

**Comment by JacobfromAVS** [comment]
sorry that I was a pain, I hope this helps others :)

**Comment by Ghostwalker83** [comment]
> I honestly have no idea why Forge is apparently allowing installs of 1.9.2, after I removed it from every location...

As I understand the structure of The Forge's Bazaar, they create copies of all listed modules on their servers, and install them from their local storage so they don't have to rely on the github server and can optimize data transfer.
That way however, removed versions will still be listed for some time.
And as a side note, they also have issues with long/complex version numbers (things like 5.3.7.2.a).

**Comment by HoelFarabee** [comment]
> Was about to write my own bug report but saw this thread. Having the same issue as Jacob.
> 
> ![Image](https://github.com/user-attachments/assets/c53e6d5a-62b5-4cc1-a762-68d0f1fb8f81)
> 
> pf2e extempore effects version 1.9.2 Foundry version 12.343
> 
> I currently have Monk's Token Bar installed and enabled. Is there an issue with having both modules on at the same time? Had them both on previously but the issue only started recently.

I have been having the same issue. Extempore effects 1.10.3 and Foundry version 13.345 - uninstalling Monk's fixed the problem, so there's definitely a module interaction issue at play.

**Comment by shemetz** [comment]
If this issue happens to you again, the module is probably locked and you probably need to reinstall. If I don't get any new comments on this I'll close it in a few months.
